server:
  http_listen_port: 8000

distributor:
  log_received_spans:
    enabled: true
  receivers:
    otlp:
      protocols:
        http:

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
